[theme]

# Primary accent for interactive elements
primaryColor = '#3A317A'

# Background color for the main content area
backgroundColor = '#0E1C2D'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#0072C0'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"